  services:
   web:
    build: ./Backend
    volumes:
        - ./swagger/swagger.yaml:/app/swagger/swagger.yaml
    environment:
        - NODE_ENV=development
    deploy:
          replicas: 3
    ports:
        - "5000"

   nginx:
    build: ./nginx
    ports:  
        - "80:80"
    depends_on:
        - web

   BD:
    image: mongo:4.4.6
    volumes:  
      - mongo-data:/data/db

  volumes:
      mongo-data:
    