openapi: 3.0.3
info:
  description: "A.P.I de Super-mercados"
  version: "1.0.0"
  title: "A.P.I de Super-mercados"
servers:
  - url: "http://localhost:5000"
    description: Servidor local
tags:
  - name: "produtos"
    description: "Operações sobre Super-mercados"
paths:
  /produtos:
    get:
      tags:
        - "produtos"
      summary: "Obter todos os produtos de Super-mercados"
      responses:
        200:
          description: "Lista de Produto"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/produtos"
    post:
      tags:
        - "produtos"
      summary: "Criar um novo produto"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/produtos"
      responses:
        201:
          description: "produtos criado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/produtos"
  /produtos/{produtosId}:
    put:
      tags:
        - "produtos"
      summary: "Atualizar um produto já existente"
      parameters:
        - name: "produtosId"
          in: "path"
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/produtos"
      responses:
        200:
          description: "produto atualizado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/produtos"
        404:
          description: "produto não identificado"
    delete:
      tags:
        - "produtos"
      summary: "Deletar um produto identificado"
      parameters:
        - name: "produtosId"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        204:
          description: "produto deletado"
        404:
          description: "produto não identificado"
components:
  schemas:
    produtos:
      type: "object"
      required:
        - "id"
        - "name"
        - "description"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        description:
          type: "string"